base_url: "https://example.com/domjudge/"
userpwd: "admin:password"

cid: 1
saved_dir: "./output/1"

exported_data:
  event_feed: false
  runs: false
  source_code: true

# Since there are too many requests to send when downloading sourcecode,
# we use `grequests` to send in parallel,
# this configuration field can set the number of parallel sending
# defaults to `100`
grequests_parallels_nums: 100

# Since Ghost Dat Data with Chinese team names may be garbled
# when imported into Codeforces,
# We found that if some dummy Russian teams are added, it may works.
# This configuration field is only for exporting ghost dat data
# defaults to `false`
add_dummy_russian_team: false
