base_url: "https://example.com/domjudge/"
userpwd: "admin:password"

cid: 1
saved_dir: "./output/1"

exported_data:
  event_feed: true
  runs: true
  submissions: true
  images: true
  ghost_dat_data: true
  resolver_data: true
  scoreboard_excel_data: true

add_dummy_russian_team: true
